"use client";

type Recipient = {
  legalName: string; businessName: string; tin: string; tinType: string;
  address1: string; address2: string; city: string; state: string; zip: string;
};

const usd = (n: number) => n.toLocaleString("en-US", { style: "currency", currency: "USD" });

export default function Form1099({ year, payerName, recipient, box1 }: {
  year: string; payerName: string; recipient: Recipient; box1: number;
}) {
  const addr = [recipient.address1, recipient.address2].filter(Boolean).join(", ");
  const cityline = [recipient.city, recipient.state].filter(Boolean).join(", ") + (recipient.zip ? " " + recipient.zip : "");

  return (
    <div className="f99-wrap">
      <div className="noprint" style={{ display: "flex", gap: 10, marginBottom: 18, flexWrap: "wrap" }}>
        <button className="btn" onClick={() => window.print()}>Save as PDF / Print</button>
        <a className="btn ghost" href="/app/tax" style={{ textDecoration: "none" }}>← Back to 1099s</a>
      </div>

      <div className="f99">
        <div className="f99-head">
          <div>
            <div className="f99-form">Form <b>1099-NEC</b></div>
            <div className="f99-rev">Tax year {year}</div>
          </div>
          <div className="f99-title">Nonemployee<br />Compensation</div>
          <div className="f99-copy">Copy B<br /><span>For Recipient</span></div>
        </div>

        <div className="f99-grid">
          <div className="f99-left">
            <div className="f99-cell">
              <span>PAYER&apos;S name, street address, city, state, ZIP code</span>
              <b>{payerName}</b>
              <div className="f99-blank">Address</div>
              <div className="f99-blank">City, State, ZIP</div>
            </div>
            <div className="f99-cell">
              <span>PAYER&apos;S TIN</span>
              <div className="f99-blank">EIN</div>
            </div>
            <div className="f99-cell">
              <span>RECIPIENT&apos;S TIN ({recipient.tinType ? recipient.tinType.toUpperCase() : "SSN/EIN"})</span>
              <b>{recipient.tin || "—"}</b>
            </div>
            <div className="f99-cell">
              <span>RECIPIENT&apos;S name</span>
              <b>{recipient.legalName || "—"}</b>
              {recipient.businessName ? <div style={{ fontSize: 12, color: "#444" }}>{recipient.businessName}</div> : null}
            </div>
            <div className="f99-cell">
              <span>Street address (including apt. no.)</span>
              <b>{addr || "—"}</b>
            </div>
            <div className="f99-cell">
              <span>City or town, state or province, country, and ZIP</span>
              <b>{cityline.trim() || "—"}</b>
            </div>
          </div>

          <div className="f99-right">
            <div className="f99-box f99-box-main">
              <span>1 &nbsp; Nonemployee compensation</span>
              <b>{usd(box1)}</b>
            </div>
            <div className="f99-box">
              <span>2 &nbsp; Payer made direct sales totaling $5,000 or more</span>
              <b>&nbsp;</b>
            </div>
            <div className="f99-box">
              <span>4 &nbsp; Federal income tax withheld</span>
              <b>{usd(0)}</b>
            </div>
            <div className="f99-row2">
              <div className="f99-box"><span>5 &nbsp; State tax withheld</span><b>{usd(0)}</b></div>
              <div className="f99-box"><span>6 &nbsp; State / Payer&apos;s state no.</span><b>&nbsp;</b></div>
            </div>
            <div className="f99-box"><span>7 &nbsp; State income</span><b>&nbsp;</b></div>
          </div>
        </div>

        <div className="f99-foot">
          Department of the Treasury — Internal Revenue Service. This document was generated by SplitKey for {payerName}. Verify all figures and complete payer details before filing. Box 1 reflects nonemployee compensation paid on completed deals in {year}.
        </div>
      </div>

      <style>{`
        .f99-wrap{max-width:820px;margin:0 auto;padding:8px 0 60px}
        .f99{background:#fff;color:#111;border:2px solid #111;border-radius:4px;font-family:Inter,Arial,sans-serif}
        .f99-head{display:flex;align-items:stretch;border-bottom:2px solid #111}
        .f99-head>div{padding:12px 16px}
        .f99-form{font-size:15px} .f99-form b{font-size:20px}
        .f99-rev{font-size:12px;color:#444;margin-top:2px}
        .f99-title{flex:1;text-align:center;font-weight:700;font-size:18px;line-height:1.15;display:flex;align-items:center;justify-content:center;border-left:1px solid #111;border-right:1px solid #111}
        .f99-copy{text-align:center;font-weight:700;font-size:15px} .f99-copy span{font-weight:400;font-size:11px;color:#444}
        .f99-grid{display:grid;grid-template-columns:1fr 1fr}
        .f99-left{border-right:2px solid #111}
        .f99-cell,.f99-box{padding:9px 14px;border-bottom:1px solid #111}
        .f99-cell span,.f99-box span{display:block;font-size:10.5px;color:#333;text-transform:uppercase;letter-spacing:.2px;margin-bottom:5px}
        .f99-cell b,.f99-box b{font-size:15px;color:#111}
        .f99-blank{height:16px;border-bottom:1px dotted #999;margin-top:6px}
        .f99-box-main b{font-size:22px}
        .f99-box-main{background:#f3f6fb}
        .f99-row2{display:grid;grid-template-columns:1fr 1fr}
        .f99-row2 .f99-box:first-child{border-right:1px solid #111}
        .f99-right .f99-box:last-child{border-bottom:none}
        .f99-foot{padding:11px 16px;font-size:10.5px;color:#444;line-height:1.5;border-top:2px solid #111}
        @media print{
          .noprint{display:none !important}
          @page{size:letter;margin:0.6in}
          body{background:#fff !important}
          .f99{box-shadow:none}
        }
      `}</style>
    </div>
  );
}
